# Copyright 2019 Alfredo de la Fuente - AvanzOSC
# License AGPL-3 - See http://www.gnu.org/licenses/agpl-3.0.html
{
    "name": "Issue education",
    "version": "12.0.4.0.0",
    "license": "AGPL-3",
    "depends": [
        "education",
        "contacts_school",
        "contacts_school_education",
        "calendar_school",
        "web_tree_duplicate",
    ],
    "author": "AvanzOSC",
    "website": "https://github.com/avanzosc/education",
    "category": "Customer Relationship Management",
    "data": [
        "security/ir.model.access.csv",
        "security/issue_education_rule.xml",
        "data/issue_education_data.xml",
        "views/calendar_event_view.xml",
        "views/res_partner_view.xml",
        "views/school_claim_view.xml",
        "views/school_issue_severity_scale_view.xml",
        "views/school_issue_type_view.xml",
        "views/school_college_issue_type_view.xml",
        "views/school_college_educational_measures_view.xml",
        "views/school_issue_site_view.xml",
        "views/school_issue_proof_view.xml",
        "views/school_issue_view.xml",
        "views/education_schedule_view.xml",
        "views/issue_education_menu_view.xml",
    ],
    "installable": True,
}
