from . import education_data
from . import education_academic_year
from . import education_academic_year_evaluation
from . import education_activity_type
from . import education_classroom
from . import education_contract_type
from . import education_course
from . import education_designation_level
from . import education_field
from . import education_group
from . import education_group_type
from . import education_idtype
from . import education_language
from . import education_level
from . import education_level_course_subject
from . import education_level_field_subject
from . import education_level_workday_type
from . import education_model
from . import education_plan
from . import education_position
from . import education_schedule
from . import education_section
from . import education_shift
from . import education_subject
from . import education_subject_type
from . import education_task_type
from . import education_work_reason
from . import education_workday_type
from . import res_lang
from . import res_partner
