from . import education_position
from . import res_partner
from . import school_claim
from . import school_college_educational_measure
from . import school_college_issue_type
from . import school_issue
from . import school_issue_proof
from . import school_issue_severity_scale
from . import school_issue_site
from . import school_issue_type
